# ABOUTME: GitHub Actions workflow for Django CI
# ABOUTME: Runs tests on push and pull request for main branch using pytest and Django

name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DJANGO_SETTINGS_MODULE: airquality.settings
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || pip install django pytest pytest-django requests
      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py migrate
      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest locationform/tests.py --ds=airquality.settings --maxfail=1 --disable-warnings -v
